### ISSUE TITLE
 400 Bad Request: {"error":"block param must be a hex int"}

### ISSUE THREAD

**Issue by mteam88** [lmittmann/flashbots#21]
`panic: 400 Bad Request: {"error":"block param must be a hex int"}`
On using `callBundle`

**Comment by lmittmann** [comment]
What is your value for `BlockNumber`? `nil`?

**Comment by mteam88** [comment]
With  a *Big.Int

**Comment by lmittmann** [comment]
You have to set the `BlockNumber` param in `flashbots.CallBundleRequest`. A block tag like "latest" is not allowed by the mev-geth API.
